using System;
using System.IO;

namespace BenchmarkDotNet.Diagnosers
{
    public class MetrionEnergyProfilerConfig
    {
        /// <param name="metrionBinaryPath">The path where Metrion binary is located.</param>
        /// <param name="metrionDatabaseDirectory">The path where Metrion exports the measurements' database.</param>
        /// <param name="metrionDatabaseNamePattern">The pattern of the Metrion database file name.</param>
        /// <param name="keepMetrionDatabaseFiles">When set to true, the database files generated by Metrion will be stored in the Artifacts folder. When set to false, the Metrion database files will be deleted after energy extraction. False by default.</param>
        /// <param name="performExtraBenchmarksRun">When set to true, benchmarks will be executed one more time with the profiler attached. If set to false, there will be no extra run but the results will contain overhead. False by default.</param>
        /// <param name="timeoutInSeconds">How long should we wait for the Metrion script to finish exporting the measurements. 300s by default.</param>
        /// <param name="measurePerIteration">
        /// When set to true, measurements are processed separately for each iteration, which may introduce additional overhead.
        /// When set to false, only a single measurement of the actual stage is performed, and the energy per iteration is approximated accordingly.
        /// </param>
        public MetrionEnergyProfilerConfig(string metrionBinaryPath, string metrionDatabaseDirectory, string metrionDatabaseNamePattern="monitor*.db", bool keepMetrionDatabaseFiles = false, bool performExtraBenchmarksRun = false, int timeoutInSeconds = 300, bool measurePerIteration = false)
        {
            MetrionBinaryPath = new FileInfo(metrionBinaryPath);
            MetrionDatabaseDirectory = new DirectoryInfo(metrionDatabaseDirectory);
            MetrionDatabaseNamePattern = metrionDatabaseNamePattern;
            KeepMetrionDatabaseFiles = keepMetrionDatabaseFiles;
            RunMode = performExtraBenchmarksRun ? RunMode.ExtraRun : RunMode.NoOverhead;
            Timeout = TimeSpan.FromSeconds(timeoutInSeconds);
            MeasurePerIteration = measurePerIteration;
        }

        public TimeSpan Timeout { get; }

        public RunMode RunMode { get; }

        public FileInfo MetrionBinaryPath { get; }

        public DirectoryInfo MetrionDatabaseDirectory { get; }
        public string MetrionDatabaseNamePattern { get; }
        public bool KeepMetrionDatabaseFiles { get; }
        public bool MeasurePerIteration { get; }
    }
}
